#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.BotBlox >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.BotBlox=/luci-static/botblox
		set luci.main.mediaurlbase=/luci-static/botblox
		commit luci
	EOF
fi

exit 0
